### ISSUE TITLE
client.run().wait() giving an C compiler error and on_voice_state_update not firing

### ISSUE THREAD

**Issue by reisxd** [Terisback/discord.v#25]
Title above ^ 
(fixed the C compiler with entering an a long time to thread sleep and changing `client.run().wait()` to `client.run()`

**Comment by Terisback** [comment]
Exact error message please.
If it says "duplicate something-something" try to compile with `-no-parallel`
It's almost common issue with compilation of multithreaded apps #24

**Comment by reisxd** [comment]
> Exact error message please. If it says "duplicate something-something" try to compile with `-no-parallel` It's almost common issue with compilation of multithreaded apps #24

Yeah, `-no-parallel` fixed it, thanks!
Another issue ive encountered is nothing works when you compile with `-prod` flag, the bot comes online and i can't run any commands.

**Comment by Terisback** [comment]
Thing with `-prod` flag, is issue with how V compiles tls related things, more like how `gcc` with `-O3` optimises it.
There is already issue in vlang/v repo I believe

**Comment by Terisback** [comment]
You can try to use different compiler, like `clang`, via `-cc clang` flag
